"""empty message

Revision ID: 505925cd5302
Revises: 89d83b5d7686
Create Date: 2021-12-14 16:57:56.553682

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '505925cd5302'
down_revision = '89d83b5d7686'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('members',
    sa.Column('server_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['server_id'], ['servers.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('members')
    # ### end Alembic commands ###
